apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - infraestructure/k8s/*
build:
  googleCloudBuild:
    projectId: ticketing-dev-305703
  artifacts:
    - image: us.gcr.io/ticketing-dev-305703/auth
      context: auth
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .